# 预备知识

## Python 基础

列表推导式

In [6]:
[i*2+j for i in range(5) for j in range(2)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
# 嵌套循环
[x + '_' + str(y+1) for x in ['a','b'] for y in range(2)]

['a_1', 'a_2', 'b_1', 'b_2']

条件赋值

In [18]:
x = [1,-1,2,-6,-7]
for i in x:
    y = 'positive' if i > 0 else 'negative'
    print(y)

positive
negative
positive
negative
negative


匿名函数

In [40]:
[(lambda x: (x+1)**2)(i) for i in range(5) ]

[1, 4, 9, 16, 25]

匿名函数映射（单值）

In [37]:
list(map(lambda x: x**3, range(5)))

[0, 1, 8, 27, 64]

匿名函数映射（多值）：注意与嵌套循环区分

In [48]:
list(map(lambda x,y:(x+1) ** (y+1),range(3),range(3)))

[1, 4, 27]

In [49]:
list(map(lambda x,y:(x+1) ** (y+1),range(2),range(3)))

[1, 4]

In [51]:
list(map(lambda x,y:(x+1) ** (y+1),range(3),range(1)))

[1]

zip对象与enumerate方法：zip是把多个列表封装在一起，enumerate是枚举单个列表，将遍历序号和对应元素绑定在一个元组中。

In [58]:
list(zip(['a','b','c'],['1','2','3']))

[('a', '1'), ('b', '2'), ('c', '3')]

In [68]:
list(enumerate(['a','b','c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

可以利用zip对象构建字典

In [66]:
subjects = ['语文','数学','英语']
grades = ['113','128','145']
dict(zip(subjects,grades))

{'语文': '113', '数学': '128', '英语': '145'}

可以利用`*`操作符将<font color = red>zip</font>对象解压

In [70]:
name = ['Alen','Beth','Ceasar']
age = ['23','15','34']
height = ['188','165','179']
zipped = list(zip(name, age, height))
zipped

[('Alen', '23', '188'), ('Beth', '15', '165'), ('Ceasar', '34', '179')]

In [72]:
list(zip(*zipped)) #解压后，三个元组对应压缩前的列表

[('Alen', 'Beth', 'Ceasar'), ('23', '15', '34'), ('188', '165', '179')]

## Numpy 基础

In [64]:
import numpy as np

In [86]:
# 生成普通的数组
print(np.array([1,2,3]))

[1 2 3]


In [44]:
# 生成矩阵
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

生成随机数组：

|函数|输出|
|:--|:--|
|np.random.rand(n)|生成服从0-1均匀分布的n个随机数|
|np.random.randn(n)|生成服从标准正态分布的n个随机数|
|np.random.randint(x,y,n)|生成位于x（包含）和y（不包含）之间的n个随机整数|
|np.random.choice(my_list,n)|在my_list中有放回地等概率抽取n个样本|
|np.random.permutation(my_list)|随机重排my_list|

In [107]:
population = ['A','B','C','D','E','F','G','H']
# 这种不放回的抽样实际上就是重新排列原来的列表
print(np.random.choice(population,8,replace = False))

['D' 'H' 'B' 'F' 'E' 'G' 'C' 'A']


In [181]:
np.random.randint(1,5,(2,3))

array([[4, 1, 3],
       [1, 2, 3]])

设置随机种子(seed)可以固定随机数的输出结果

In [202]:
np.random.seed(0)
print(np.random.rand(3))
print(np.random.randn(3))
print(np.random.randint(1,100,3))

[0.5488135  0.71518937 0.60276338]
[-2.2683282   1.33354538 -0.84272405]
[71 89 89]


在与二维数组进行合并操作时，一维数组应当被视为**列向量**，但此时只能实现`c_`按列合并，而无法实现`r_`按行合并。

In [17]:
np.c_[np.zeros((2,1)),np.array([0,0])]

array([[0., 0.],
       [0., 0.]])

In [19]:
# 这个例子中，两个元素看似形状相同，但无法实现按行合并
try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


形状相同的一维数组之间既可以按行合并，又可以按列合并。

In [29]:
# 按列合并时，两个一维数组均视为列向量
np.c_[np.array([1,2]),np.array([3,4])]

array([[1, 3],
       [2, 4]])

In [30]:
# 按行合并时，两个一维数组均视为行向量
np.r_[np.array([1,2]),np.array([3,4])]

array([1, 2, 3, 4])

可以通过`reshape`方法实现数组维度变换，参数`order`取值为`'C'`时逐行填充原数组元素，取值为`'F'`时逐列填充

In [34]:
# 逐行填充
np.arange(6).reshape((2,3),order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
# 逐列填充
np.arange(6).reshape((2,3),order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [38]:
# 逐列填充（简化）
np.arange(6).reshape((2,-1),order='F')

array([[0, 2, 4],
       [1, 3, 5]])

可利用`reshape(-1)`将任意维度的数组转化为1维数组。其中
将**n\*1维**数组转为**1维**数组的操作是经常使用的：

In [55]:
a = np.ones((3,1))
print('Before:')
print(a)

b = a.reshape(-1)
print('After:')
print(b)

Before:
[[1.]
 [1.]
 [1.]]
After:
[1. 1. 1.]


In [57]:
c = np.array([[1,2],[3,4]])
print(c.reshape(-1))

[1 2 3 4]


In [79]:
print(c)

[[1 2]
 [3 4]]


`axis`参数，取值为0时代表**列**，取值为1时代表**行**。

In [81]:
# 按列加总
c.sum(0)

array([4, 6])

In [80]:
# 按行加总
c.sum(1)

array([3, 7])

In [68]:
c.max()

4

向量与矩阵的计算：

In [84]:
# 向量内积，方法1
np.array([1,2,3]).dot(np.array([3,2,1]))

10

In [82]:
# 向量内积，方法2
np.array([1,2,3]) @ np.array([3,2,1])

10

In [112]:
# 矩阵乘法
np.array([[1,2],[3,4]]) @ np.array([[1,3],[2,4]])

array([[ 5, 11],
       [11, 25]])

矩阵相关参数：

In [6]:
mat1 = np.array([[1,2,3],[4,5,6]])
# 输出矩阵的形状
mat1.shape

(2, 3)

## 练习

### Ex1: 利用列表推导式写矩阵乘法

In [71]:
# 题目
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
# 利用嵌套循环实现矩阵乘法
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
            res[i][j] = item

((M1@M2 - res) < 1e-15).all() # 排除数值误差

True

思路：列表推导式实际上是对循环操作的简化。在实现矩阵乘法的过程中，涉及3层嵌套循环，因此列表推导式也应该有3层嵌套。

In [78]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)

# 利用3层列表嵌套改写上述的循环过程
def pro(t1,t2):
    # step 1: 将计算结果排成一列，其中包括列表嵌套列表，以及3层循环
    raw =[sum([t1[i][k]*t2[k][j] for k in range(t1.shape[1])]) for i in range(t1.shape[0]) for j in range(t2.shape[1])]
    # step 2: 变形
    out = np.array(raw).reshape(t1.shape[0],-1)
    return out
((M1@M2 - pro(M1,M2)) < 1e-15).all() # 排除数值误差

True

### Ex2: 更新矩阵

思路：先生成`1/A`，然后按行求和，得到更新所需元素。之后循环更新。

In [125]:
def ud(m):
    t = (1/m).sum(1)
    return (m.T * t).T

In [126]:
A = np.arange(1,10).reshape(3,-1)

In [127]:
ud(A)

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

### Ex3: 卡方统计量

思路：定义$m\times1$维行加总向量以及$1\times n$维列加总向量，二者进行矩阵相乘，所得元素均除以原矩阵全元素之和，即可生成矩阵$B_{m \times n}$.

关键：利用`reshape(1,-1)`和`reshape(-1,1)`来快速实现将一维数组转换为二维的行向量和列向量。

In [132]:
np.random.seed(0)
A = np.random.randint(10,20,(8,5))
A

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11]])

In [206]:
def my_chi(m):
    # 行加总
    mr = m.sum(1).reshape(-1,1)
    # 列加总
    mc = m.sum(0).reshape(1,-1)
    # 生成矩阵B
    b = (mr @ mc)/m.sum()
    # 生成卡方统计量
    chi = (m-b)**2/b
    return chi.sum()

In [207]:
my_chi(A)

11.842696601945802

### Ex4: 改进矩阵计算功能

In [229]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))

思路：可以利用`np.linalg.norm(x,ord)`来计算范数。具体来说，$\|x-y\|_2$可以利用`np.linalg.norm(x-y,2)`来计算。

In [236]:
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = np.linalg.norm(B[i]-U[:,j],2)**2
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)

In [237]:
solution(B,U,Z)

100566.0

### Ex5: 连续整数的最大长度

目标：输入一个整数数组，返回其中**递增连续**整数子数组的最大长度

这题想了好久，没有明确思路。

## 练习答案

### Ex1: 用列表推导式写矩阵乘法

In [261]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]
((M1@M2 - res) < 1e-15).all()

True

### Ex2: 更新矩阵

注意：`a*b`表示数组`a`与数组`b`<font color = red>对应位置</font>的元素分别相乘。

本题的解答需要运用广播机制，同时还需将一维数组转换为二维列向量。

In [265]:
A = np.arange(1,10).reshape(3,-1)
B = A*(1/A).sum(1).reshape(-1,1)
B

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

### Ex3: 卡方统计量

In [266]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))
B = A.sum(0)*A.sum(1).reshape(-1, 1)/A.sum()
res = ((A-B)**2/B).sum()
res

11.842696601945802

### Ex4: 改进矩阵计算功能

本题同样需要利用数组计算的<font color=red>广播机制</font>来构造符合要求的二维数组。

为了实现逐元素相乘求和，需要构建满足要求的矩阵$Y_{m\times n}$，其中每个元素$Y_{ij}$满足：

$$
\begin{align}
Y_{ij} &= \|B_i-U_j\|_2^2 \\
     &= \sum_{k=1}^p (B_{ik}-U_{kj})^2 \\
     &= \sum_{k=1}^pB_{ik}^2+\sum_{k=1}^pU_{kj}^2-2\sum_{k=1}^pB_{ik}U_{kj}
\end{align}
$$

从上式可以看出，$Y_{ij}$可以分解为三部分：矩阵$B$第$i$行元素的平方和，矩阵$U$第$j$列元素的平方和，以及$(B\times U)_{ij}$的$-2$倍。

关键：把矩阵$B$的行平方和数组视为列向量（需要变形），把矩阵$U$的列平方和视为行向量（无需变形）。

In [267]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))

In [272]:
(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum()

100566

In [273]:
%timeit -n 30 solution(B, U, Z)

79.1 ms ± 1.45 ms per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [274]:
%timeit -n 30 (((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum()

532 µs ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 30 loops each)


可以看到，改进后的计算速度大幅提升了。

### Ex5: 连续整数的最大长度

In [275]:
f = lambda x:np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()

In [277]:
f([1,2,5,6,7])

3

In [278]:
f([3,2,1,2,3,4,6])

4

步骤拆解：

In [299]:
x = [1,2,5,6,7]
# 标记“断点”
np.diff(x)!=1

array([False,  True, False, False])

In [300]:
# 按列合并，首尾均设为1
np.r_[1,np.diff(x)!=1,1]

array([1, 0, 1, 0, 0, 1], dtype=int32)

In [301]:
# 标记连续递增整数的起点（包含）和终点（不包含）位置
np.nonzero(np.r_[1,np.diff(x)!=1,1])

(array([0, 2, 5], dtype=int64),)

In [302]:
# 计算每个连续递增数列的长度
np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1]))

array([[2, 3]], dtype=int64)

In [303]:
# 得到最大长度
np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()

3